### ISSUE TITLE
Orb attempts to install TailScale even if it's already installed

### ISSUE THREAD

**Issue by michael-careplanner** [threecommaio/circleci-tailscale#1]
Currently, this orb attempts to install TailScale even if it's already installed. For example in our CI/CD pipelines we use a custom alpine container for deployments that already has all the tools we need for a deployment installed, including TailScale.

It would be good if the orb detected if tailscale was already installed and skipped the install process if it was.

**Comment by chrisgoffinet** [comment]
Good point, thanks! Approved
